"""
Dash Web Application for Financial Metrics Visualization.

This script defines the Dash application layout and callbacks for visualizing
financial data related to Microstrategy (MSTR), its calculated Market Net
Asset Value (MNAV), and Bitcoin (BTC-USD) prices.

The application reads pre-processed historical data from 'mstr_historical_mnav.csv',
which is expected to be generated by the 'financial_tracker.py' script.
It uses Plotly for charting and Dash for the web framework.

This module is intended to be imported by a separate server script (e.g., main.py)
which will handle running the Dash/Flask server and any API endpoints.
"""

import dash
from dash import Dash, dcc, html, Input, Output
import pandas as pd
import logging # For logging errors in data loading and app operations
import plotly.graph_objects as go
# Imports for API endpoint (Flask, request, jsonify, os) are removed as endpoint is removed.
# Import for perform_daily_data_update is removed as it's not called by Dash UI directly.

# Note: Logging is expected to be configured by the script that runs this app (e.g., main.py)
# or by financial_tracker.py if its functions are used by callbacks (though not directly here).


# --- Data Preparation Functions ---

def load_historical_data(csv_filepath: str = "mstr_historical_mnav.csv") -> pd.DataFrame:
    """
    Loads historical MSTR price, BTC price, and MNAV data from a CSV file.

    The CSV file is expected to have 'Date' as its first column, which will be
    used as the DataFrame index and parsed as datetime objects.

    Args:
        csv_filepath (str, optional): The path to the CSV file.
                                      Defaults to "mstr_historical_mnav.csv", assuming
                                      it's located in the same directory as app.py.

    Returns:
        pd.DataFrame: A pandas DataFrame with 'Date' as the index. Expected columns
                      include 'Close_MSTR', 'Close_BTC', and 'MNAV'.
                      Returns an empty DataFrame if the file is not found or any
                      other error occurs during loading.
    """
    try:
        # Read CSV, using 'Date' column as index and parsing it as datetime objects
        data = pd.read_csv(csv_filepath, index_col='Date', parse_dates=True)
        logging.info(f"Successfully loaded data from {csv_filepath} for Dash app.") # Clarified log
        # Basic validation: check for expected columns
        expected_cols = ['Close_MSTR', 'Close_BTC', 'MNAV']
        if not all(col in data.columns for col in expected_cols):
            logging.warning(f"Dash app: Loaded data from {csv_filepath} is missing one or more expected columns: {expected_cols}. Found columns: {list(data.columns)}")
        return data
    except FileNotFoundError:
        logging.error(f"Dash app: Error - The data file {csv_filepath} was not found.")
        return pd.DataFrame()
    except Exception as e:
        logging.error(f"Dash app: An error occurred while loading data from {csv_filepath}: {e}", exc_info=True)
        return pd.DataFrame()

def calculate_bollinger_bands(data_series: pd.Series, window: int = 20, num_std_dev: int = 2) -> pd.DataFrame:
    """
    Calculates Bollinger Bands (SMA, Upper Band, Lower Band) for a given pandas Series.

    Args:
        data_series (pd.Series): The input time series data (e.g., MNAV values).
        window (int, optional): The rolling window period for calculating the
                                Simple Moving Average (SMA) and standard deviation.
                                Defaults to 20.
        num_std_dev (int, optional): The number of standard deviations to use for
                                     the upper and lower bands. Defaults to 2.

    Returns:
        pd.DataFrame: A DataFrame with columns: 'Original' (the input data_series),
                      'SMA' (Simple Moving Average), 'UpperBand', and 'LowerBand'.
                      Returns an empty DataFrame if the input is not a valid Series,
                      is empty, or if other issues occur.
    """
    if not isinstance(data_series, pd.Series):
        logging.error("Dash app: Invalid input - data_series must be a pandas Series for Bollinger Bands calculation.")
        return pd.DataFrame()
    if data_series.empty:
        logging.warning("Dash app: Input data_series is empty. Cannot calculate Bollinger Bands.")
        return pd.DataFrame()
    if len(data_series) < window:
        logging.warning(f"Dash app: Data series length ({len(data_series)}) is less than window size ({window}). Bollinger Bands will have many NaNs initially.")

    df_bb = pd.DataFrame()
    df_bb['Original'] = data_series
    df_bb['SMA'] = data_series.rolling(window=window, min_periods=1).mean()
    rolling_std = data_series.rolling(window=window, min_periods=1).std()
    df_bb['UpperBand'] = df_bb['SMA'] + (rolling_std * num_std_dev)
    df_bb['LowerBand'] = df_bb['SMA'] - (rolling_std * num_std_dev)

    logging.info(f"Dash app: Successfully calculated Bollinger Bands for series with window {window} and {num_std_dev} std dev.")
    return df_bb

# Initialize the Dash application
# __name__ is a special Python variable that gives the name of the current module.
# Dash uses this to know where to find assets if you have a local 'assets' folder.
app = Dash(__name__)
server = app.server # Expose Flask server instance for potential WSGI deployment by main.py

# Define the layout of the application
# The layout is composed of a tree of Dash Components (like html.Div, dcc.Graph, etc.).
app.layout = html.Div(children=[
    # Hidden Store component to trigger the initial callback on page load
    dcc.Store(id='initial-load-trigger'),

    # Main title of the dashboard
    html.H1(children="Financial Metrics Dashboard"),

    # Subtitle or introductory text for the dashboard
    html.Div(children='''
        A dashboard for visualizing Microstrategy (MSTR) stock price,
        its Bitcoin-based Market Net Asset Value (MNAV), and Bitcoin (BTC-USD) data.
    '''),

    # Section for Chart 1: MSTR Price and MNAV
    html.H2(children="MSTR Price vs. MNAV"),
    dcc.Graph(
        id='mstr-mnav-chart', # ID for the graph component, used in callbacks
        # Initial figure is empty; it will be populated by the callback
        figure={
            'data': [],
            'layout': {
                'title': 'MSTR Market Price and Calculated MNAV Over Time',
                'paper_bgcolor': 'rgba(0,0,0,0)',
                'plot_bgcolor': 'rgba(0,0,0,0)',
                'font': {'color': '#7FDBFF'}
            }
        }
    ),

    # Section for Chart 2: MNAV with Bollinger Bands
    html.H2(children="MNAV with Bollinger Bands"),
    dcc.Graph(
        id='mnav-bollinger-chart', # ID for the graph component
        figure={
            'data': [],
            'layout': {
                'title': 'MNAV with Bollinger Bands',
                'paper_bgcolor': 'rgba(0,0,0,0)',
                'plot_bgcolor': 'rgba(0,0,0,0)',
                'font': {'color': '#7FDBFF'}
            }
        }
    ),

    # Section for Chart 3: Bitcoin Price
    html.H2(children="Bitcoin (BTC-USD) Price"),
    dcc.Graph(
        id='btc-price-chart', # ID for the graph component
        figure={
            'data': [],
            'layout': {
                'title': 'Bitcoin (BTC-USD) Price Over Time',
                'paper_bgcolor': 'rgba(0,0,0,0)',
                'plot_bgcolor': 'rgba(0,0,0,0)',
                'font': {'color': '#7FDBFF'}
            }
        }
    )
])

# --- Callbacks ---
# This single callback updates all three charts.
# It's triggered by the 'initial-load-trigger' Store component when the app loads.
@app.callback(
    [Output('mstr-mnav-chart', 'figure'),      # Output for the first chart
     Output('mnav-bollinger-chart', 'figure'), # Output for the second chart
     Output('btc-price-chart', 'figure')],     # Output for the third chart
    [Input('initial-load-trigger', 'data')]    # Input (dummy) to trigger on load
)
def update_all_charts(initial_trigger_data) -> tuple[go.Figure, go.Figure, go.Figure]:
    """
    Loads historical data and generates/updates all Plotly chart figures for the dashboard.

    This callback is triggered once when the app loads due to the 'initial-load-trigger'
    Store component. Its 'data' argument is not used but serves to initiate the callback.

    Args:
        initial_trigger_data: Data from the dcc.Store component. Its value is not
                              material for this callback, which acts as an on-load trigger.

    Returns:
        tuple[go.Figure, go.Figure, go.Figure]: A tuple containing the three Plotly
                                                figure objects for the charts.
                                                Returns empty figures if data loading fails.
    """
    logging.info("Dash app: Callback update_all_charts triggered.") # Clarified log source
    df = load_historical_data() # Load data from "mstr_historical_mnav.csv"

    # Define common layout properties for a consistent dark theme across charts
    dark_layout_props = {
        'template': 'plotly_dark',             # Use Plotly's dark theme as a base
        'paper_bgcolor': 'rgba(40,40,40,0.8)', # Background of the entire chart area
        'plot_bgcolor': 'rgba(20,20,20,0.8)',   # Background of the plotting area itself
        'font': {'color': '#FFFFFF'},          # Default font color for titles, axes, legends
        'legend_title_font_color': 'white',
        'xaxis_title_font_color': 'white',
        'yaxis_title_font_color': 'white',
        'hovermode': 'x unified'               # Unified tooltip for all traces at a given x-value
    }

    # Default empty figure to return in case of errors or no data
    empty_fig_layout = go.Layout(title_text="Data not available", **dark_layout_props)
    empty_fig = go.Figure(layout=empty_fig_layout)

    if df.empty:
        logging.warning("Dash app: Historical data is empty. Returning empty charts for all outputs.")
        return empty_fig, empty_fig, empty_fig

    # --- Chart 1: MSTR Price and MNAV ---
    fig1 = go.Figure()
    # Add MSTR closing price trace
    if 'Close_MSTR' in df.columns:
        fig1.add_trace(go.Scatter(x=df.index, y=df['Close_MSTR'], mode='lines', name='MSTR Price', line=dict(color='royalblue')))
    else:
        logging.warning("Dash app: Column 'Close_MSTR' not found in data for Chart 1.")
    # Add MNAV trace
    if 'MNAV' in df.columns:
        fig1.add_trace(go.Scatter(x=df.index, y=df['MNAV'], mode='lines', name='MNAV (USD)', line=dict(color='cyan')))
    else:
        logging.warning("Dash app: Column 'MNAV' not found in data for Chart 1.")
    # Update layout for Chart 1
    fig1.update_layout(
        title_text='MSTR Price vs. MNAV Over Time',
        xaxis_title='Date', yaxis_title='Value (USD)',
        legend_title_text='Legend',
        **dark_layout_props # Apply common dark theme
    )

    # --- Chart 2: MNAV with Bollinger Bands ---
    fig2 = go.Figure()
    if 'MNAV' in df.columns and not df['MNAV'].empty:
        df_bb = calculate_bollinger_bands(df['MNAV']) # Defaults: window=20, num_std_dev=2
        if not df_bb.empty:
            # Plot Bollinger Bands fill area first (semi-transparent)
            fig2.add_trace(go.Scatter(x=df_bb.index, y=df_bb['UpperBand'], mode='lines', line=dict(width=0.5, color='rgba(173,216,230,0.0)'), showlegend=False, name='Upper Bound Fill'))
            fig2.add_trace(go.Scatter(x=df_bb.index, y=df_bb['LowerBand'], mode='lines', line=dict(width=0.5, color='rgba(173,216,230,0.0)'), fill='tonexty', fillcolor='rgba(173,216,230,0.2)', showlegend=False, name='Lower Bound Fill'))

            fig2.add_trace(go.Scatter(x=df_bb.index, y=df_bb['Original'], mode='lines', name='MNAV', line=dict(color='blue')))
            fig2.add_trace(go.Scatter(x=df_bb.index, y=df_bb['SMA'], mode='lines', name='SMA (20-day)', line=dict(color='orange')))

            fig2.add_trace(go.Scatter(x=df_bb.index, y=df_bb['UpperBand'], mode='lines', line=dict(dash='dash', color='lightgrey'), name='Upper Band'))
            fig2.add_trace(go.Scatter(x=df_bb.index, y=df_bb['LowerBand'], mode='lines', line=dict(dash='dash', color='lightgrey'), name='Lower Band'))
        else:
            logging.warning("Dash app: Bollinger Bands calculation returned empty DataFrame for Chart 2.")
    else:
        logging.warning("Dash app: Column 'MNAV' not found or is empty; cannot generate Bollinger Bands chart.")
    # Update layout for Chart 2
    fig2.update_layout(
        title_text='MNAV with Bollinger Bands (20-day, 2 Std Dev)',
        xaxis_title='Date', yaxis_title='Value (USD)',
        legend_title_text='Legend',
        **dark_layout_props # Apply common dark theme
    )

    # --- Chart 3: Bitcoin Price ---
    fig3 = go.Figure()
    # Add BTC closing price trace
    if 'Close_BTC' in df.columns:
        fig3.add_trace(go.Scatter(x=df.index, y=df['Close_BTC'], mode='lines', name='BTC Price', line=dict(color='gold')))
    else:
        logging.warning("Dash app: Column 'Close_BTC' not found in data for Chart 3.")
    # Update layout for Chart 3
    fig3.update_layout(
        title_text='Bitcoin (BTC-USD) Price Over Time',
        xaxis_title='Date', yaxis_title='Price (USD)',
        legend_title_text='Legend',
        **dark_layout_props # Apply common dark theme
    )

    logging.info("Dash app: Successfully generated and styled all chart figures.")
    return fig1, fig2, fig3

# The if __name__ == '__main__': block and API endpoint related code are removed.
# This script is now intended to be imported as a module by main.py.
